require 'cherrypicker/cherrypick'
require 'cherrypicker/linkchecker'
require 'cherrypicker/helpers'
require 'cherrypicker/plugins/vimeo'
require 'cherrypicker/plugins/rapidshare'
require 'cherrypicker/plugins/hotfile'
require 'cherrypicker/plugins/youtube'
require 'cherrypicker/plugins/megavideo'
require "cherrypicker/plugins/rghost"
require "cherrypicker/plugins/fileserve"
require "cherrypicker/plugins/googlevideo"
